description = "actuator-example – a example of actuator."

dependencies {
    api project(":actuator")

    compileOnly "com.diffblue.cover:cover-annotations:1.7.0"

    testImplementation "com.diffblue.cover:cover-annotations:1.7.0"
    testImplementation "org.springframework:spring-test:5.3.18"
}

